run:
  timeout: 5m
  go: "1.21"

linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 120

linters:
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - lll
    - unconvert
    - unparam
    - gosec
    - shadow
  disable:
  settings:
    errcheck:
      exclude-functions:
        - viper.BindPFlag
        - viper.GetString
        - viper.GetBool
        - viper.GetStringMap
        - viper.GetStringMapString
        - viper.GetStringMapStringSlice

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - lll 