# Sample configuration file for note-compiler
# Copy this to ~/.note-compiler.yaml to use

# Output file path - REQUIRED on command line if not specified here
# Uses Go template syntax:
# {{.Home}} - Home directory
# {{.Date "format"}} - Current date/time with Go time format
# {{.Env "VAR"}} - Environment variable
output_file_path: "{{.Home}}/compiled_notes/notes_{{.Date \"2006-01-02_150405\"}}.txt"

# Glob patterns - REQUIRED on command line if not specified here
# These define which files will be included in the compilation
# Patterns starting with ! are exclusion patterns
glob_patterns:
  - "{{.Home}}/Documents/My Vault/**/*.md"
  - "!{{.Home}}/Documents/My Vault/Archive/**"
  - "!{{.Home}}/Documents/My Vault/.obsidian/**"
  - "!**/_resources/**"
  - "!**/.*"  # Hidden files

# Show excluded files in output (optional)
# list_excluded: true

# Examples of Go date formats:
# {{.Date "2006-01-02"}}           -> 2024-03-15
# {{.Date "2006-01-02_150405"}}    -> 2024-03-15_143022
# {{.Date "Jan 02, 2006"}}         -> Mar 15, 2024
# {{.Date "Monday, Jan 2 2006"}}   -> Friday, Mar 15 2024

# Examples of paths:
# {{.Home}}/notes/daily_{{.Date "2006-01-02"}}.md
# {{.Env "WORKSPACE"}}/compiled/notes.txt
# /tmp/notes_{{.Date "20060102_150405"}}.txt
