# Configuration file for note-compiler
# Location: ~/.note-compiler.yaml

# Output file path using Go templates:
# {{.Home}} - Home directory
# {{.Date "format"}} - Current date/time with Go time format
# {{.Env "VAR"}} - Environment variable
output_file_path: "{{.Home}}/compiled_notes/notes_{{.Date \"2006-01-02_150405\"}}.txt"

# Include patterns (Go templates supported)
include_patterns:
  - "{{.Home}}/Documents/**/*.md"
  - "{{.Home}}/notes/**/*.txt"
  - "{{.Env \"PROJECTS_DIR\"}}/**/*.md"

# Exclude patterns (Go templates supported) 
exclude_patterns:
  - "**/node_modules/**"
  - "**/.*"  # Hidden files
  - "**/.git/**"
  - "{{.Home}}/Documents/private/**"

# Copy to clipboard after compilation
copy_to_clipboard: true

# Examples of Go date formats:
# {{.Date "2006-01-02"}}           -> 2024-03-15
# {{.Date "2006-01-02_150405"}}    -> 2024-03-15_143022
# {{.Date "Jan 02, 2006"}}         -> Mar 15, 2024
# {{.Date "Monday, Jan 2 2006"}}   -> Friday, Mar 15 2024

# Examples of paths:
# {{.Home}}/notes/daily_{{.Date "2006-01-02"}}.md
# {{.Env "WORKSPACE"}}/compiled/notes.txt
# /tmp/notes_{{.Date "20060102_150405"}}.txt
